/**
 * Shared slice pipeline utilities.
 */

const fs = require('node:fs');
const path = require('node:path');
const { EXTENSIONS } = require('../../config/constants');

/**
 * Build set of supported input extensions.
 * @returns {Set<string>} Lowercase extension whitelist.
 */
function getSupportedInputExtensions() {
    return new Set([
        ...EXTENSIONS.direct,
        ...EXTENSIONS.cad,
        ...EXTENSIONS.image,
        ...EXTENSIONS.vector,
        ...EXTENSIONS.archive
    ]);
}

/**
 * Check whether an extension is accepted by the slice pipeline.
 * @param {string} extension File extension including dot.
 * @returns {boolean} True when extension is supported.
 */
function isSupportedInputExtension(extension) {
    if (!extension) return false;
    return getSupportedInputExtensions().has(extension.toLowerCase());
}

/**
 * Render supported input extensions as human-readable CSV string.
 * @returns {string} Comma-separated sorted extension list.
 */
function getSupportedInputExtensionsText() {
    return Array.from(getSupportedInputExtensions()).sort((a, b) => a.localeCompare(b)).join(', ');
}

/**
 * Normalize output base filename for safe filesystem usage.
 * @param {string} fileName Original uploaded filename.
 * @returns {string} Sanitized base name.
 */
function sanitizeOutputBaseName(fileName) {
    const parsedName = path.parse(fileName || '').name;
    const normalized = parsedName
        .trim()
        .replaceAll(/[^a-zA-Z0-9]+/g, '-')
        .replaceAll(/(^-+)|(-+$)/g, '');

    return normalized || 'output';
}

/**
 * Build deterministic output artifact filename.
 * @param {string} originalFileName Original uploaded file name.
 * @param {'FDM'|'SLA'} technology Active technology.
 * @returns {string} Generated output file name.
 */
function buildOutputFilename(originalFileName, technology) {
    const extension = technology === 'SLA' ? 'sl1' : 'gcode';
    const baseName = sanitizeOutputBaseName(originalFileName);
    const uniqueSuffix = Date.now();

    return `${baseName}-output-${uniqueSuffix}.${extension}`;
}

/**
 * Round finite numeric value to 3 decimals.
 * @param {number} value Input numeric value.
 * @returns {number} Rounded number or `0` for non-finite values.
 */
function roundToThree(value) {
    if (!Number.isFinite(value)) return 0;
    return Math.round(value * 1000) / 1000;
}

/**
 * Round XYZ dimension object to 3 decimal precision.
 * @param {{x: number, y: number, z: number}} dimensions Raw dimensions.
 * @returns {{x: number, y: number, z: number}} Rounded dimensions.
 */
function roundDimensions(dimensions) {
    return {
        x: roundToThree(dimensions.x),
        y: roundToThree(dimensions.y),
        z: roundToThree(dimensions.z)
    };
}

/**
 * Resolve the newest output file for extension in a directory.
 * @param {string} outputDir Output directory path.
 * @param {string} extension Extension filter (e.g. `.gcode`).
 * @returns {string | null} Latest matching file path or null.
 */
function resolveLatestOutputFile(outputDir, extension) {
    if (!fs.existsSync(outputDir)) return null;

    const candidates = fs.readdirSync(outputDir)
        .filter((name) => name.toLowerCase().endsWith(extension))
        .map((name) => {
            const filePath = path.join(outputDir, name);
            const stat = fs.statSync(filePath);
            return {
                filePath,
                mtimeMs: stat.mtimeMs
            };
        })
        .sort((a, b) => b.mtimeMs - a.mtimeMs);

    return candidates[0]?.filePath || null;
}

/**
 * Rename Orca-produced output file to the API-generated target name.
 * @param {string | null} generatedOutputPath Path generated by slicer.
 * @param {string} desiredOutputPath Target output path.
 * @returns {string} Final output path.
 */
function alignOrcaOutputFileName(generatedOutputPath, desiredOutputPath) {
    if (!generatedOutputPath || !fs.existsSync(generatedOutputPath)) {
        throw new Error('Orca did not produce a .gcode output file.');
    }

    if (generatedOutputPath === desiredOutputPath) {
        return desiredOutputPath;
    }

    if (fs.existsSync(desiredOutputPath)) {
        fs.unlinkSync(desiredOutputPath);
    }

    fs.renameSync(generatedOutputPath, desiredOutputPath);
    return desiredOutputPath;
}

/**
 * Remove transient Orca metadata file from output directory.
 * @param {string} outputDir Output directory path.
 * @returns {void}
 */
function cleanupOrcaResultMetadata(outputDir) {
    const resultMetadataPath = path.join(outputDir, 'result.json');
    if (!fs.existsSync(resultMetadataPath)) return;

    try {
        fs.unlinkSync(resultMetadataPath);
    } catch (error_) {
        console.warn(`[WARN] Could not remove Orca metadata file (${resultMetadataPath}): ${error_.message}`);
    }
}

/**
 * Delete temporary files/directories created for request processing.
 * @param {string[]} fileList Paths to remove.
 * @returns {void}
 */
function cleanupFiles(fileList) {
    fileList.forEach((file) => {
        if (file && fs.existsSync(file)) {
            try {
                if (fs.lstatSync(file).isDirectory()) {
                    fs.rmSync(file, { recursive: true, force: true });
                    console.log(`[CLEANUP] Deleted directory: ${file}`);
                } else {
                    fs.unlinkSync(file);
                    console.log(`[CLEANUP] Deleted file: ${file}`);
                }
            } catch (err) {
                console.error(`[CLEANUP ERROR] Could not delete ${file}: ${err.message}`);
            }
        }
    });
}

module.exports = {
    isSupportedInputExtension,
    getSupportedInputExtensionsText,
    buildOutputFilename,
    roundToThree,
    roundDimensions,
    resolveLatestOutputFile,
    alignOrcaOutputFileName,
    cleanupOrcaResultMetadata,
    cleanupFiles
};
